<?php

/**
 * @file
 * Advanced aggregation css compression module.
 *
 */

/**
 * Default value to see if this will compress aggregated files.
 */
define('ADVAGG_CSS_COMPRESS_AGG_FILES', TRUE);

/**
 * Default value for which css compression library to use.
 */
define('ADVAGG_CSS_COMPRESSOR', 2);

/**
 * Implement hook_advagg_get_hooks_hash_alter.
 */
function advagg_css_compress_advagg_get_hooks_hash_alter(&$advagg_hash) {
  $advagg_hash['variables']['advagg_css_compressor'] = variable_get('advagg_css_compressor', ADVAGG_CSS_COMPRESSOR);
  $advagg_hash['variables']['advagg_css_compress_agg_files'] = variable_get('advagg_css_compress_agg_files', ADVAGG_CSS_COMPRESS_AGG_FILES);
}
